# Generated by Django 3.1.3 on 2020-12-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat',
            field=models.IntegerField(choices=[('cashout', 'CASH OUT'), ('payment', 'PAYMENT'), ('cashin', 'CASHIN'), ('transfer', 'TRANSFER'), ('debit', 'DEBIT')], default='cashout'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_dest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_org',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance_dest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance_org',
            field=models.IntegerField(),
        ),
    ]
