# Generated by Django 3.1.3 on 2020-12-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0005_auto_20201216_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('cashout', 'CASH OUT'), ('payment', 'PAYMENT'), ('cashin', 'CASH IN'), ('transfer', 'TRANSFER'), ('debit', 'DEBIT')], default='cashout', max_length=20),
        ),
    ]
