# Generated by Django 3.1.3 on 2020-12-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0006_auto_20201219_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cat',
            field=models.IntegerField(default=0),
        ),
    ]
