# Generated by Django 3.1.3 on 2020-12-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0008_auto_20201219_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
    ]
