# Generated by Django 3.1.4 on 2020-12-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0011_transaction_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_dest',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_org',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance_dest',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance_org',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='testing',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
