# Generated by Django 3.1.3 on 2020-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0014_auto_20201222_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='nameDest',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nameOrig',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
