# Generated by Django 3.1.3 on 2020-12-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0015_auto_20201222_2033'),
        ('fraud', '0004_auto_20201219_1100'),
    ]

    operations = [
    ]
