# Generated by Django 3.1.4 on 2020-12-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0009_auto_20201219_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('old_balance_org', models.IntegerField()),
                ('new_balance_org', models.IntegerField()),
                ('old_balance_dest', models.IntegerField()),
                ('new_balance_dest', models.IntegerField()),
                ('transfer_type', models.CharField(choices=[('cashout', 'CASH OUT'), ('payment', 'PAYMENT'), ('cashin', 'CASH IN'), ('transfer', 'TRANSFER'), ('debit', 'DEBIT')], default='cashout', max_length=20)),
                ('cat', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
