# Generated by Django 3.1.4 on 2020-12-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0010_auto_20201221_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='testing',
            field=models.CharField(default='safe', max_length=200),
        ),
    ]
