# Generated by Django 3.1.3 on 2020-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0013_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='nameDest',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nameOrig',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='step',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='cashout', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_dest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_org',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance_dest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance_org',
            field=models.FloatField(default=0),
        ),
    ]
